//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES__
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTES__()
        {
            this.COMENTARIOs = new HashSet<COMENTARIO>();
            this.COMPROBANTE_FISCAL = new HashSet<COMPROBANTE_FISCAL>();
            this.ENTREGAS_ = new HashSet<ENTREGAS_>();
            this.FACTURAs = new HashSet<FACTURA>();
            this.HISTORIAL_COMPRA_ = new HashSet<HISTORIAL_COMPRA_>();
            this.LISTADO_PAQUETE_COMPRA_ = new HashSet<LISTADO_PAQUETE_COMPRA_>();
            this.LOG_ACTION_CLIENTE = new HashSet<LOG_ACTION_CLIENTE>();
            this.MENSAJE__ = new HashSet<MENSAJE__>();
            this.NOTIFICACION_ = new HashSet<NOTIFICACION_>();
            this.SALA_USUARIO__ = new HashSet<SALA_USUARIO__>();
            this.STATUS_COMPRA_ = new HashSet<STATUS_COMPRA_>();
            this.TARJETA_MEMBRESIA_ = new HashSet<TARJETA_MEMBRESIA_>();
            this.TARJETA_REGALO_ = new HashSet<TARJETA_REGALO_>();
        }
    
        public int ClienteId { get; set; }
        public string nombreCliente { get; set; }
        public string apellidoCliente { get; set; }
        public string imagenCliente { get; set; }
        public int teléfonoCliente { get; set; }
        public int códigoPostalCliente { get; set; }
        public System.DateTime fechaNacimientoCliente { get; set; }
        public int generoId { get; set; }
        public int tipoDocumentoId { get; set; }
        public int numeroDocumentoCliente { get; set; }
        public string correoCliente { get; set; }
        public string contraseñaCliente { get; set; }
        public bool estado { get; set; }
        public bool emailMarketing { get; set; }
    
        public virtual GENERO GENERO { get; set; }
        public virtual TIPO_DOCUMENTO TIPO_DOCUMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMENTARIO> COMENTARIOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPROBANTE_FISCAL> COMPROBANTE_FISCAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTREGAS_> ENTREGAS_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_COMPRA_> HISTORIAL_COMPRA_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTADO_PAQUETE_COMPRA_> LISTADO_PAQUETE_COMPRA_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_ACTION_CLIENTE> LOG_ACTION_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAJE__> MENSAJE__ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICACION_> NOTIFICACION_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALA_USUARIO__> SALA_USUARIO__ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STATUS_COMPRA_> STATUS_COMPRA_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARJETA_MEMBRESIA_> TARJETA_MEMBRESIA_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARJETA_REGALO_> TARJETA_REGALO_ { get; set; }
    }
}
