//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES__
    {
        public int UsuarioId { get; set; }
        public string nombreCliente { get; set; }
        public string apellidoCliente { get; set; }
        public string imagenCliente { get; set; }
        public int teléfonoCliente { get; set; }
        public int códigoPostalCliente { get; set; }
        public System.DateTime fechaNacimientoCliente { get; set; }
        public int generoId { get; set; }
        public int tipoDocumentoId { get; set; }
        public int numeroDocumentoCliente { get; set; }
        public string correoCliente { get; set; }
        public string contraseñaCliente { get; set; }
        public bool estado { get; set; }
        public bool emailMarketing { get; set; }
    
        public virtual GENERO GENERO { get; set; }
        public virtual TIPO_DOCUMENTO TIPO_DOCUMENTO { get; set; }
    }
}
