//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMENTARIO
    {
        public int comentarioId { get; set; }
        public int ClienteId { get; set; }
        public int productoId { get; set; }
        public short estrellaComentario { get; set; }
        public string mensajeComentario { get; set; }
    
        public virtual CLIENTES__ CLIENTES__ { get; set; }
        public virtual PRODUCTO__ PRODUCTO__ { get; set; }
    }
}
