//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA__
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPRA__()
        {
            this.ENTREGAS_ = new HashSet<ENTREGAS_>();
        }
    
        public int comprasId { get; set; }
        public int carritoComprasId { get; set; }
        public decimal precioInicialCompra { get; set; }
        public decimal subTotalCompraITBIS { get; set; }
        public int tarjetaCreditoId { get; set; }
        public Nullable<int> cuponesId { get; set; }
        public Nullable<int> descuentoId { get; set; }
        public string direccion { get; set; }
        public int metodoEnvioId { get; set; }
        public decimal totalPago { get; set; }
        public bool estado { get; set; }
    
        public virtual CARRITO_COMPRAS_ CARRITO_COMPRAS_ { get; set; }
        public virtual CUPONES_ CUPONES_ { get; set; }
        public virtual DESCUENTOS_ DESCUENTOS_ { get; set; }
        public virtual METODO_ENVIO METODO_ENVIO { get; set; }
        public virtual TARJETA_CREDITO_ TARJETA_CREDITO_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTREGAS_> ENTREGAS_ { get; set; }
    }
}
