//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORREO_EMAIL_MARKETING_
    {
        public int correoEmailMarketingId { get; set; }
        public string tituloMensaje { get; set; }
        public string imagenCorreoEmailMarketing { get; set; }
        public string contenidoCorreoEmailMarketing { get; set; }
        public System.DateTime fechaCreacionCorreoEmailMarketing { get; set; }
    }
}
