//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUPONES_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUPONES_()
        {
            this.COMPRA__ = new HashSet<COMPRA__>();
        }
    
        public int cuponesId { get; set; }
        public string nombreCupones { get; set; }
        public Nullable<decimal> descuentoCupones { get; set; }
        public Nullable<decimal> precioDescontar { get; set; }
        public System.DateTime fechaVencimiento { get; set; }
        public string codigoCupones { get; set; }
        public string imagenCupones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA__> COMPRA__ { get; set; }
    }
}
