//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESCUENTOS_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DESCUENTOS_()
        {
            this.COMPRA__ = new HashSet<COMPRA__>();
            this.PRODUCTO__1 = new HashSet<PRODUCTO__>();
        }
    
        public int descuentoId { get; set; }
        public int productoId { get; set; }
        public int categoriaProductoId { get; set; }
        public int usuarioId { get; set; }
        public decimal descuentoAplicar { get; set; }
        public System.DateTime fechaExpiracionDescuento { get; set; }
    
        public virtual CATEGORIA_PRODUCTO CATEGORIA_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA__> COMPRA__ { get; set; }
        public virtual PRODUCTO__ PRODUCTO__ { get; set; }
        public virtual USUARIO__ USUARIO__ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO__> PRODUCTO__1 { get; set; }
    }
}
