//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIA_FERIADO_
    {
        public int diaFeriadoId { get; set; }
        public string nombreDiaFeriado { get; set; }
        public System.DateTime fechaDiaFeriado { get; set; }
        public bool seLabora { get; set; }
        public System.DateTime horarioAperturaDiaFeriado { get; set; }
        public System.DateTime horarioCierreDiaFeriad { get; set; }
    }
}
