//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESAS__
    {
        public int usuarioId { get; set; }
        public string razonSocialEmpresa { get; set; }
        public string telefonoEmpresa { get; set; }
        public string imagenEmpresa { get; set; }
        public int codigoPostalEmpresa { get; set; }
        public int RNC { get; set; }
        public string correoEmpresa { get; set; }
        public string contraseñaEmpresa { get; set; }
        public bool estado { get; set; }
        public bool emailMarketing { get; set; }
    }
}
