//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTREGAS_
    {
        public int entregaId { get; set; }
        public int comprasId { get; set; }
        public int usuarioId { get; set; }
        public int mensajeroEncargadoId { get; set; }
        public string ubicacionActualEntrega { get; set; }
        public string ubicacionDestinoEntrega { get; set; }
        public int statusTipoCompraId { get; set; }
        public string firmaClientePaqueteCompra { get; set; }
        public bool statusFirmaEntregaPaqueteCompra { get; set; }
    
        public virtual COMPRA__ COMPRA__ { get; set; }
        public virtual TIPO_STATUS_COMPRA TIPO_STATUS_COMPRA { get; set; }
        public virtual USUARIO__ USUARIO__ { get; set; }
        public virtual USUARIO__ USUARIO__1 { get; set; }
    }
}
