//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADISTICAS_
    {
        public int estadisticasId { get; set; }
        public int tipoEstadisticasId { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string documentoEstadisticas { get; set; }
    
        public virtual TIPO_ESTADISTICAS_ TIPO_ESTADISTICAS_ { get; set; }
    }
}
