//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public int factura1 { get; set; }
        public int supermercadoId { get; set; }
        public int ClienteId { get; set; }
        public int comprasId { get; set; }
        public int carritoComprasId { get; set; }
        public System.DateTime fecha { get; set; }
        public bool statusTarjetaCredito { get; set; }
        public bool comprobanteFiscal { get; set; }
        public Nullable<int> comprobanteFiscalId { get; set; }
    
        public virtual CARRITO_COMPRAS_ CARRITO_COMPRAS_ { get; set; }
        public virtual CLIENTES__ CLIENTES__ { get; set; }
        public virtual COMPRA__ COMPRA__ { get; set; }
        public virtual SUPERMERCADO_ SUPERMERCADO_ { get; set; }
    }
}
