//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_COMPRA_
    {
        public int historialCompraId { get; set; }
        public int usuarioId { get; set; }
        public string nombreCliente { get; set; }
        public string razonSocialEmpresa { get; set; }
        public int carritoCompraId { get; set; }
        public System.DateTime fechaEnvio { get; set; }
        public bool estadoTipoHistorialCompra { get; set; }
        public decimal totalPago { get; set; }
    
        public virtual CARRITO_COMPRAS_ CARRITO_COMPRAS_ { get; set; }
        //public virtual HISTORIAL_COMPRA_ HISTORIAL_COMPRA_1 { get; set; }
        //public virtual HISTORIAL_COMPRA_ HISTORIAL_COMPRA_2 { get; set; }
        public virtual USUARIO__ USUARIO__ { get; set; }
    }
}
