//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_PRODUCTO_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LISTA_PRODUCTO_()
        {
            this.CARRITO_COMPRAS_ = new HashSet<CARRITO_COMPRAS_>();
        }
    
        public int listaProductosId { get; set; }
        public int productoId { get; set; }
        public decimal precioProducto { get; set; }
        public decimal totalPago { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARRITO_COMPRAS_> CARRITO_COMPRAS_ { get; set; }
        public virtual PRODUCTO__ PRODUCTO__ { get; set; }
    }
}
