//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTADO_PAQUETE_COMPRA_
    {
        public int listadoPaqueteCompraId { get; set; }
        public int usuarioId { get; set; }
        public string nombreCliente { get; set; }
        public string razonSocialEmpresa { get; set; }
        public int carritoComprasId { get; set; }
        public decimal totalPago { get; set; }
        public bool estadoListadoPaqueteCompra { get; set; }
        public System.DateTime fechaCreacionPaqueteCompra { get; set; }
        public bool errorReportado { get; set; }
        public string mensajePaqueteCompra { get; set; }
        public bool statusFirmaEntregaPaqueteCompra { get; set; }
        public string firmaClientePaqueteCompra { get; set; }
        public string ubicacionActualPaqueteCompra { get; set; }
        public string ubicacionDestinoPaqueteCompra { get; set; }
    
        public virtual CARRITO_COMPRAS_ CARRITO_COMPRAS_ { get; set; }
        public virtual USUARIO__ USUARIO__ { get; set; }
    }
}
