//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_ACTION_CLIENTE
    {
        public int LogId { get; set; }
        public int tipoNotificacionId { get; set; }
        public int tipoEstadisticasId { get; set; }
        public int ClienteId { get; set; }
        public System.DateTime fechaEjecución { get; set; }
    
        public virtual CLIENTES__ CLIENTES__ { get; set; }
        public virtual TIPO_ESTADISTICAS_ TIPO_ESTADISTICAS_ { get; set; }
        public virtual TIPO_NOTIFICACION_ TIPO_NOTIFICACION_ { get; set; }
    }
}
