//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENSAJE__
    {
        public int mensajeId { get; set; }
        public int usuarioId { get; set; }
        public int salaId { get; set; }
        public string mensaje { get; set; }
        public System.DateTime fecha { get; set; }
        public int tipoMensajeId { get; set; }
        public int tipoSalaId { get; set; }
        public string url_link { get; set; }
    
        public virtual SALA__ SALA__ { get; set; }
        public virtual TIPO_MENSAJE__ TIPO_MENSAJE__ { get; set; }
        public virtual TIPO_SALA__ TIPO_SALA__ { get; set; }
        public virtual USUARIO__ USUARIO__ { get; set; }
    }
}
