//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREGUNTAS_FRECUENTES_
    {
        public int preguntasFrecuentesId { get; set; }
        public string preguntaPreguntasFrecuentes { get; set; }
        public string respuestaPreguntasFrecuentes { get; set; }
    }
}
