//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO__
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO__()
        {
            this.COMENTARIOs = new HashSet<COMENTARIO>();
            this.DESCUENTOS_ = new HashSet<DESCUENTOS_>();
            this.LISTA_PRODUCTO_ = new HashSet<LISTA_PRODUCTO_>();
        }
    
        public int productoId { get; set; }
        public string nombreProducto { get; set; }
        public string imagenProducto { get; set; }
        public int cantidadProducto { get; set; }
        public int sucursalId { get; set; }
        public int supermercadoId { get; set; }
        public decimal precioProducto { get; set; }
        public Nullable<int> descuentoId { get; set; }
        public Nullable<decimal> precioAnterior { get; set; }
        public int categoriaProductoId { get; set; }
        public string descripcionProducto { get; set; }
        public string tablaNutricionalProductoIMG { get; set; }
    
        public virtual CATEGORIA_PRODUCTO CATEGORIA_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMENTARIO> COMENTARIOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESCUENTOS_> DESCUENTOS_ { get; set; }
        public virtual DESCUENTOS_ DESCUENTOS_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTA_PRODUCTO_> LISTA_PRODUCTO_ { get; set; }
        public virtual SUCURSAL_ SUCURSAL_ { get; set; }
        public virtual SUPERMERCADO_ SUPERMERCADO_ { get; set; }
    }
}
