//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALA_USUARIO__
    {
        public int salaUsuarioId { get; set; }
        public int salaId { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public Nullable<int> ClienteId { get; set; }
    
        public virtual CLIENTES__ CLIENTES__ { get; set; }
        public virtual SALA__ SALA__ { get; set; }
        public virtual USUARIO__ USUARIO__ { get; set; }
    }
}
