//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOBRE_NOSOTROS_
    {
        public int sobreNosotrosId { get; set; }
        public string quienesSomosSobreNosotros { get; set; }
        public string misionSobreNosotros { get; set; }
        public string visionSobreNosotros { get; set; }
        public string valoresSobreNosotros { get; set; }
    }
}
