//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_COMPRA_
    {
        public int statusCompraId { get; set; }
        public int usuarioId { get; set; }
        public string nombreCliente { get; set; }
        public string razonSocialEmpresa { get; set; }
        public int carritoComprasId { get; set; }
        public decimal totalPago { get; set; }
        public int statusTipoCompraId { get; set; }
        public int mensajeroStatusCompra { get; set; }
    
        public virtual TIPO_STATUS_COMPRA TIPO_STATUS_COMPRA { get; set; }
        public virtual USUARIO__ USUARIO__ { get; set; }
        public virtual USUARIO__ USUARIO__1 { get; set; }
    }
}
