//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPERMERCADO_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUPERMERCADO_()
        {
            this.FACTURAs = new HashSet<FACTURA>();
            this.PRODUCTO__ = new HashSet<PRODUCTO__>();
            this.SUCURSAL_ = new HashSet<SUCURSAL_>();
        }
    
        public int supermercadoId { get; set; }
        public string nombreSupermercado { get; set; }
        public string direccionSupermercado { get; set; }
        public System.DateTime horarioApertura { get; set; }
        public System.DateTime horarioCierre { get; set; }
        public bool diaFeriado { get; set; }
        public System.DateTime horarioAperturaSabado { get; set; }
        public System.DateTime horarioCierreSabado { get; set; }
        public System.DateTime horarioAperturaDomingo { get; set; }
        public System.DateTime horarioCierreDomingo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO__> PRODUCTO__ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUCURSAL_> SUCURSAL_ { get; set; }
    }
}
