//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARJETA_REGALO_
    {
        public int tarjetaRegaloId { get; set; }
        public int ClienteId { get; set; }
        public string nombreCliente { get; set; }
        public string razonSocialEmpresa { get; set; }
        public decimal valorAcreditarTarjetaRegalo { get; set; }
        public System.DateTime fechaVencimiento { get; set; }
    
        public virtual CLIENTES__ CLIENTES__ { get; set; }
    }
}
