//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARJETA_MEMBRESIA_
    {
        public int tarjetaMembresiaId { get; set; }
        public int usuarioId { get; set; }
        public string nombreCliente { get; set; }
        public string razonSocialEmpresa { get; set; }
        public int puntosAcumuladosTarjetaMembresia { get; set; }
        public System.DateTime fechaVencimientoTarjetaMembresia { get; set; }
    
        public virtual USUARIO__ USUARIO__ { get; set; }
    }
}
