//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkaDo_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO__
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO__()
        {
            this.DESCUENTOS_ = new HashSet<DESCUENTOS_>();
            this.ENTREGAS_ = new HashSet<ENTREGAS_>();
            this.LOG_ACTION_USUARIO = new HashSet<LOG_ACTION_USUARIO>();
            this.MENSAJE__ = new HashSet<MENSAJE__>();
            this.SALA_USUARIO__ = new HashSet<SALA_USUARIO__>();
        }
    
        public int usuarioId { get; set; }
        public string nombreUsuario { get; set; }
        public string apellidoUsuario { get; set; }
        public string imagenUsuario { get; set; }
        public string cedulaUsuario { get; set; }
        public int generoId { get; set; }
        public string correoCorporativoUsuario { get; set; }
        public string telefonoUsuario { get; set; }
        public int sucursalId { get; set; }
        public int rolId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESCUENTOS_> DESCUENTOS_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTREGAS_> ENTREGAS_ { get; set; }
        public virtual GENERO GENERO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_ACTION_USUARIO> LOG_ACTION_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAJE__> MENSAJE__ { get; set; }
        public virtual ROL_USUARIO ROL_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALA_USUARIO__> SALA_USUARIO__ { get; set; }
        public virtual SUCURSAL_ SUCURSAL_ { get; set; }
    }
}
